import { expect, test } from "@playwright/test";

test("single ZIP configuration keeps separate routes, prompts and persists after reload", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: /Abrir configuración global/i }).click();
  const dialog = page.getByRole("dialog");
  const section = dialog.locator("article").filter({ has: page.getByRole("heading", { name: "ZIP único con progreso y reanudación", exact: true }) });
  const toggle = section.getByRole("checkbox", { name: "Activar ZIP único" });
  await expect(toggle).toBeEnabled();
  await expect(toggle).not.toBeChecked();
  const headings = await dialog.locator(".settings-section-stack > article h4").allTextContents();
  expect(headings.indexOf("ZIP único con progreso y reanudación")).toBe(headings.indexOf("Descargas") + 1);
  expect(headings.indexOf("Reporte")).toBe(headings.indexOf("ZIP único con progreso y reanudación") + 1);
  const comments = section.getByLabel("URL · Comentarios · ZIP único");
  const helix = section.getByLabel("URL · Incidencias · ZIP único");
  await expect(comments).toHaveValue("");
  await expect(helix).toHaveValue("");
  await toggle.check();
  await expect(toggle).toBeChecked();
  await comments.fill("https://chatgpt.com/g/comments-single");
  await comments.blur();
  await expect(section.getByRole("link", { name: "Abrir Comentarios · ZIP único" })).toHaveAttribute("href", "https://chatgpt.com/g/comments-single");
  await helix.fill("https://chatgpt.com/g/helix-single");
  await helix.blur();
  await expect(section.getByRole("link", { name: "Abrir Incidencias · ZIP único" })).toBeVisible();
  await section.getByText("Ver instrucciones de Clasifica comentarios", {exact:true}).click();
  await expect(section.getByLabel("Instrucciones de Clasifica comentarios")).toContainText("ENTREGAS Y REANUDACIÓN");
  await expect(section.getByLabel("Instrucciones de Clasifica comentarios")).toContainText("espera «Sí»");
  await page.reload();
  await page.getByRole("button", { name: /Abrir configuración global/i }).click();
  await expect(toggle).toBeChecked();
  await expect(comments).toHaveValue("https://chatgpt.com/g/comments-single");
  await expect(helix).toHaveValue("https://chatgpt.com/g/helix-single");
  await section.screenshot({path:testInfo.outputPath("single-zip-settings.png")});
  await toggle.uncheck();
  await expect(toggle).not.toBeChecked();
  expect(errors).toEqual([]);
});
