import { expect, test } from "@playwright/test";

test("single ZIP configuration keeps separate routes, prompts and persists after reload", async ({ page, request }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const reset = await request.put("/api/taxonomy/discovery", {data:{single_zip_enabled:false,classifier_single_zip_url:"",helix_single_zip_url:""}});
  expect(reset.ok()).toBeTruthy();
  await page.goto("/");
  await page.getByRole("button", { name: /Abrir configuración global/i }).click();
  const dialog = page.getByRole("dialog");
  const section = dialog.locator("article").filter({ has: page.getByRole("heading", { name: "ZIP único con progreso y reanudación", exact: true }) });
  const toggle = section.getByRole("switch", { name: "Activar ZIP único" });
  await expect(toggle).toBeEnabled();
  await expect(toggle).not.toBeChecked();
  const headings = await dialog.locator(".settings-section-stack > article h4").allTextContents();
  expect(headings.indexOf("ZIP único con progreso y reanudación")).toBe(headings.indexOf("Descargas") + 1);
  expect(headings.indexOf("Reporte")).toBe(headings.indexOf("ZIP único con progreso y reanudación") + 1);
  await expect(section.getByRole("textbox")).toHaveCount(0);
  await expect(section.getByRole("button")).toHaveCount(0);
  await section.screenshot({path:testInfo.outputPath("single-zip-settings.png")});
  await page.getByRole("button", { name: /Cerrar configuración/i }).click();
  await page.getByRole("button", { name: /Taxonomy Studio/i }).click();
  await page.getByRole("tab", { name: "Análisis con LLM" }).click();
  const comments = page.getByLabel("URL · Clasifica comentarios", {exact:true});
  const helix = page.getByLabel("URL · Clasifica incidencias", {exact:true});
  await expect(comments).toBeVisible();
  const originalComments = await comments.inputValue();
  const originalHelix = await helix.inputValue();
  async function changeMode(enabled: boolean) {
    await page.getByRole("button", { name: /Abrir configuración global/i }).click();
    await toggle.click();
    await expect(toggle).toBeChecked({checked:enabled});
    await expect(toggle).toBeEnabled();
    await page.getByRole("button", { name: /Cerrar configuración/i }).click();
  }
  await changeMode(true);
  await expect(comments).toHaveValue("");
  await expect(helix).toHaveValue("");
  await comments.fill("https://chatgpt.com/g/comments-single");
  await comments.blur();
  await expect(page.getByRole("link", { name: "Abrir Clasifica comentarios", exact:true })).toHaveAttribute("href", "https://chatgpt.com/g/comments-single");
  await helix.fill("https://chatgpt.com/g/helix-single");
  await helix.blur();
  await expect(page.getByRole("link", { name: "Abrir Clasifica incidencias", exact:true })).toHaveAttribute("href", "https://chatgpt.com/g/helix-single");
  await page.getByText("Ver instrucciones de Clasifica comentarios", {exact:true}).click();
  await expect(page.getByLabel("Instrucciones de Clasifica comentarios")).toHaveValue(/ENTREGAS Y REANUDACIÓN/);
  await expect(page.getByLabel("Instrucciones de Clasifica comentarios")).toHaveValue(/espera «Sí»/);
  await page.getByText("Ver instrucciones de Clasifica incidencias", {exact:true}).click();
  await expect(page.getByLabel("Instrucciones de Clasifica incidencias")).toHaveValue(/ENTREGAS Y REANUDACIÓN/);
  await page.reload();
  await page.getByRole("button", { name: /Abrir configuración global/i }).click();
  await expect(toggle).toBeChecked();
  await page.getByRole("button", { name: /Cerrar configuración/i }).click();
  await page.getByRole("button", { name: /Taxonomy Studio/i }).click();
  await page.getByRole("tab", { name: "Análisis con LLM" }).click();
  await expect(comments).toHaveValue("https://chatgpt.com/g/comments-single");
  await expect(helix).toHaveValue("https://chatgpt.com/g/helix-single");
  await changeMode(false);
  await expect(comments).toHaveValue(originalComments);
  await expect(helix).toHaveValue(originalHelix);
  await page.getByText("Ver instrucciones de Clasifica comentarios", {exact:true}).click();
  await expect(page.getByLabel("Instrucciones de Clasifica comentarios")).not.toHaveValue(/ENTREGAS Y REANUDACIÓN/);
  expect(errors).toEqual([]);
});
