// Generated by scripts/prepare_brand.py
const BRAND = Object.freeze({
  "name": "BBVA Banca de Empresas e Instituciones",
  "initiative": "bIA",
  "initiative_name": "Banca Inteligente y Autónoma",
  "initiative_credit": "Impulsado por",
  "newsletter_prefix": "[bIA]",
  "font": "Benton Sans BBVA",
  "email_signature": "<table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-top:28px;border-top:1px solid #d3d8e0;width:100%\"><tr><td style=\"padding:18px 14px 0 0;width:58px;vertical-align:middle;font:700 28px 'Benton Sans BBVA',Arial,sans-serif;color:#070e46\">bIA</td><td style=\"padding:18px 0 0;vertical-align:middle;font:12px 'Benton Sans BBVA',Arial,sans-serif;color:#52627a\">Impulsado por<br><strong style=\"color:#070e46\">Banca Inteligente y Autónoma</strong></td></tr></table>"
});
