// Generated by scripts/prepare_brand.py
export const BRAND = {
  "name": "BBVA Banca de Empresas e Instituciones",
  "initiative": "bIA",
  "initiative_name": "Banca Inteligente y Autónoma",
  "initiative_credit": "Impulsado por",
  "newsletter_prefix": "[bIA]",
  "font": "Benton Sans BBVA"
} as const;
