#!/usr/bin/env python3
"""Build browser fonts and brand artwork once; runtime consumers only read assets."""

import json
import subprocess
import sys
from base64 import b64encode
from pathlib import Path

from fontTools.ttLib import TTFont
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from nps_lens.design.brand import (  # noqa: E402
    BRAND,
    BRAND_ASSETS,
    EMAIL_CORPORATE_HEADING,
    EMAIL_DARK_CSS,
    EMAIL_HERO_COLOR,
    EMAIL_HERO_STYLE,
    EMAIL_HERO_TEXT_CLOSE,
    EMAIL_HERO_TEXT_OPEN,
    EMAIL_LIGHT_META,
    SIGNATURE_CSS,
    email_signature,
)


def main():
    fonts = ROOT / "frontend/public/assets/fonts/bbva"
    source = ROOT / "assets/ppt/bbva/fonts"
    for weight in ("Book", "Medium", "Bold"):
        font = TTFont(source / f"BentonSansBBVA-{weight}.ttf", recalcTimestamp=False)
        font.flavor = "woff2"
        font.save(fonts / f"BentonSansBBVA-{weight}.woff2")
    assets = ROOT / "frontend/public/assets/brand"
    bia_source = ROOT / "frontend/src/assets/brand/bia.svg"
    BRAND_ASSETS.mkdir(parents=True, exist_ok=True)
    (BRAND_ASSETS / "bbva-bei.png").write_bytes((assets / "bbva-bei.png").read_bytes())
    with Image.open(assets / "bbva-bei.png") as logo:
        dark = Image.new("RGBA", logo.size, "#070e46")
        dark.putalpha(logo.convert("RGBA").getchannel("A"))
        dark.save(BRAND_ASSETS / "bbva-bei-dark.png", optimize=True)
    subprocess.run(
        [
            "node",
            str(ROOT / "scripts/render_brand.cjs"),
            str(bia_source),
            str(BRAND_ASSETS / "bia.png"),
        ],
        check=True,
    )
    with Image.open(BRAND_ASSETS / "bia.png") as artwork:
        artwork.resize((144, 88), Image.Resampling.LANCZOS).save(
            BRAND_ASSETS / "bia-email.png", optimize=True
        )
    logo = b64encode((BRAND_ASSETS / "bia-email.png").read_bytes()).decode()
    (ROOT / "frontend/src/brand.css").write_text(
        "/* Generated by scripts/prepare_brand.py */\n" + SIGNATURE_CSS
    )
    (ROOT / "frontend/src/brand.ts").write_text(
        "// Generated by scripts/prepare_brand.py\nexport const BRAND = "
        + json.dumps(BRAND, ensure_ascii=False, indent=2)
        + " as const;\n"
    )
    (ROOT / "webapp/apps-script/00_Brand.gs").write_text(
        "// Generated by scripts/prepare_brand.py\nconst BRAND = Object.freeze("
        + json.dumps(
            {
                **BRAND,
                "email_dark_css": EMAIL_DARK_CSS,
                "email_hero_color": EMAIL_HERO_COLOR,
                "email_hero_style": EMAIL_HERO_STYLE,
                "email_hero_text_open": EMAIL_HERO_TEXT_OPEN,
                "email_hero_text_close": EMAIL_HERO_TEXT_CLOSE,
                "email_light_meta": EMAIL_LIGHT_META,
                "email_signature": email_signature("cid:bia-logo"),
                "initiative_logo": logo,
                "email_corporate_heading": EMAIL_CORPORATE_HEADING,
            },
            ensure_ascii=False,
            indent=2,
        )
        + ");\n"
    )
    css = ["<style>", "/* Generated by scripts/prepare_brand.py */"]
    for weight, number in (("Book", 400), ("Medium", 500), ("Bold", 700)):
        encoded = b64encode((fonts / f"BentonSansBBVA-{weight}.woff2").read_bytes()).decode()
        css.append(
            f'@font-face{{font-family:"{BRAND["font"]}";src:url("data:font/woff2;base64,{encoded}") format("woff2");font-weight:{number};font-style:normal;font-display:swap}}'
        )
    for key, file, mime in (
        ("bbva-bei-logo", assets / "bbva-bei.png", "image/png"),
        ("bia-logo", bia_source, "image/svg+xml"),
    ):
        encoded = b64encode(file.read_bytes()).decode()
        css.append(f':root{{--asset-{key}:url("data:{mime};base64,{encoded}")}}')
    css.append(SIGNATURE_CSS)
    css.append("</style>")
    (ROOT / "webapp/apps-script/BrandIdentity.html").write_text("\n".join(css) + "\n")


if __name__ == "__main__":
    main()
