#!/usr/bin/env python3
"""Build browser fonts and brand artwork once; runtime consumers only read assets."""

import json
import sys
from base64 import b64encode
from io import BytesIO
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from nps_lens.design.brand import BRAND, BRAND_ASSETS, EMAIL_SIGNATURE, SIGNATURE_CSS  # noqa: E402


def main():
    fonts = ROOT / "frontend/public/assets/fonts/bbva"
    source = ROOT / "assets/ppt/bbva/fonts"
    for weight in ("Book", "Medium", "Bold"):
        font = TTFont(source / f"BentonSansBBVA-{weight}.ttf", recalcTimestamp=False)
        font.flavor = "woff2"
        font.save(fonts / f"BentonSansBBVA-{weight}.woff2")
    # Outline the wordmark from WOFF2, so every device sees identical lettering.
    font = TTFont(fonts / "BentonSansBBVA-Bold.woff2", recalcTimestamp=False)
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    advance = 0
    paths = []
    for char in BRAND["initiative"]:
        glyph = glyphs[cmap[ord(char)]]
        pen = SVGPathPen(glyphs)
        glyph.draw(pen)
        paths.append(f'<path transform="translate({advance},0)" d="{pen.getCommands()}"/>')
        advance += glyph.width
    units = font["head"].unitsPerEm
    body = f'<g transform="translate(0,{units}) scale(1,-1)">{"".join(paths)}</g>'
    assets = ROOT / "frontend/public/assets/brand"
    svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {advance} {units*1.12}" fill="#ffffff">{body}</svg>'
    (assets / "bia-light.svg").write_text(svg)
    BRAND_ASSETS.mkdir(parents=True, exist_ok=True)
    (BRAND_ASSETS / "bbva-bei.png").write_bytes((assets / "bbva-bei.png").read_bytes())
    # PowerPoint uses the same outlined letters, rasterized at print resolution.
    font.flavor = None
    ttf = BytesIO()
    font.save(ttf)
    face = ImageFont.truetype(BytesIO(ttf.getvalue()), 192)
    bounds = face.getbbox(BRAND["initiative"])
    for variant, color in (("dark", "#070e46"), ("light", "#ffffff")):
        image = Image.new("RGBA", (bounds[2] - bounds[0] + 4, bounds[3] - bounds[1] + 4))
        ImageDraw.Draw(image).text(
            (2 - bounds[0], 2 - bounds[1]), BRAND["initiative"], font=face, fill=color
        )
        image.save(BRAND_ASSETS / f"bia-{variant}.png", optimize=True)
    (ROOT / "frontend/src/brand.css").write_text(
        "/* Generated by scripts/prepare_brand.py */\n" + SIGNATURE_CSS
    )
    (ROOT / "frontend/src/brand.ts").write_text(
        "// Generated by scripts/prepare_brand.py\nexport const BRAND = "
        + json.dumps(BRAND, ensure_ascii=False, indent=2)
        + " as const;\n"
    )
    (ROOT / "webapp/apps-script/00_Brand.gs").write_text(
        "// Generated by scripts/prepare_brand.py\nconst BRAND = Object.freeze("
        + json.dumps({**BRAND, "email_signature": EMAIL_SIGNATURE}, ensure_ascii=False, indent=2)
        + ");\n"
    )
    css = ["<style>", "/* Generated by scripts/prepare_brand.py */"]
    for weight, number in (("Book", 400), ("Medium", 500), ("Bold", 700)):
        encoded = b64encode((fonts / f"BentonSansBBVA-{weight}.woff2").read_bytes()).decode()
        css.append(
            f'@font-face{{font-family:"{BRAND["font"]}";src:url("data:font/woff2;base64,{encoded}") format("woff2");font-weight:{number};font-style:normal;font-display:swap}}'
        )
    for key, file, mime in (
        ("bbva-bei-logo", "bbva-bei.png", "image/png"),
        ("bia-logo", "bia-light.svg", "image/svg+xml"),
    ):
        encoded = b64encode((assets / file).read_bytes()).decode()
        css.append(f':root{{--asset-{key}:url("data:{mime};base64,{encoded}")}}')
    css.append(SIGNATURE_CSS)
    css.append("</style>")
    (ROOT / "webapp/apps-script/BrandIdentity.html").write_text("\n".join(css) + "\n")


if __name__ == "__main__":
    main()
